### ISSUE TITLE
"inspired by" links

### ISSUE THREAD

**Issue by jspaaks** [ardc-fair-checklist/ardc-fair-checklist.github.io#66]
code state: d447c22d3bf175dea68f0cf917c53f743d9efe1b

![image](https://user-images.githubusercontent.com/4558105/231192215-da41fe39-1693-4f28-8651-649cde1b201b.png)

**Comment by tom-h** [comment]
Just waiting for a response and then lets discuss

**Comment by tom-h** [comment]
Still waiting...

**Comment by jspaaks** [comment]
Preamble now includes link to FAIR data self assessment tool, this issue can be closed
