### ISSUE TITLE
Add links to DOI, pURL, SWHID, Handle

### ISSUE THREAD

**Issue by jspaaks** [ardc-fair-checklist/ardc-fair-checklist.github.io#68]
code state: d447c22d3bf175dea68f0cf917c53f743d9efe1b

![image](https://user-images.githubusercontent.com/4558105/231193137-225aa2dd-b71b-47a8-8f78-22f4b9cb75a9.png)

![image](https://user-images.githubusercontent.com/4558105/231193212-469f56f6-bf17-436b-b1b6-b9e3b254400a.png)

**Comment by jspaaks** [comment]
So I started implementing some of these changes, but the linkification quickly gets out of hand if you want to do it consistently. Maybe it's better if we just make "persistent identifier" a hyperlink and leave the rest?

**Comment by jspaaks** [comment]
I went ahead and used https://www.dpconline.org/handbook/technical-solutions-and-tools/persistent-identifiers. Another option would be to use the wikipedia page, although it doesn't list Handle https://en.wikipedia.org/wiki/Persistent_identifier

**Comment by jspaaks** [comment]
I would like to close this issue, what do you think @tom-h?

**Comment by tom-h** [comment]
Actually, it would be good to point to something that includes SWHIDs. Maybe this: https://doi.org/10.15497/RDA00053  ...it's not a very consumable resource.

**Comment by jspaaks** [comment]
Instead of [https://doi.org/10.15497/RDA00053](https://doi.org/10.15497/RDA00053), I've updated the wiki page to include SWHIDs

**Comment by tom-h** [comment]
Hehe, fine :-)
