### ISSUE TITLE
Consider removing the "Docker image" option

### ISSUE THREAD

**Issue by jspaaks** [ardc-fair-checklist/ardc-fair-checklist.github.io#74]
code state: d447c22d3bf175dea68f0cf917c53f743d9efe1b

![image](https://user-images.githubusercontent.com/4558105/231204170-0d7feccc-1f8c-499f-bc2f-61aafc165896.png)

![image](https://user-images.githubusercontent.com/4558105/231204417-25b71302-49e4-49c8-994a-8ff344b2963b.png)

**(About option b above):**

![image](https://user-images.githubusercontent.com/4558105/231204533-1e3ba13b-cbce-4ea1-ac53-3993459c17c5.png)

**(About option c above):**

![image](https://user-images.githubusercontent.com/4558105/231204983-6695bca2-ad44-4d93-b583-efb9be452ec6.png)

**(About making software actually executable):**

![image](https://user-images.githubusercontent.com/4558105/231447469-7726a016-e7e8-4ca7-b46a-b749c8655663.png)

**Comment by jspaaks** [comment]
Found some more dependency-free options here https://packaging.python.org/en/latest/overview/#id16:

1. Docker https://www.docker.com/
2. Podman https://podman.io/
3. AppImage https://appimage.org/
4. Flatpak https://flatpak.org/
5. Snapcraft https://snapcraft.io/about

**Comment by jspaaks** [comment]
Just to clarify this a bit more, authors can choose to package their software in various ways, some more robust than others. If I understand it correctly, the selling point of Docker, Podman, AppImage, Flatpak, and Snapcraft is that they bundle all OS dependencies with the author's software, making it more reproducible and more robust.

**Comment by tom-h** [comment]
The first answer seems like something no one would ever choose. "the software is available as is. No attempt is made to make the software easily executed." seems like its a more realistic expression of what happens.

The second answer is good. Or good enough.

In my opinion, the third answer goes too far. I'm not comfortable dictating a specific technical approach or technology as more FAIR. I reiterate what I said back in the google doc. I think we must stop at the second answer.

**Comment by jspaaks** [comment]
Updated as per your suggestions, closing this issue
