### ISSUE TITLE
Revisit scoping of the checklist

### ISSUE THREAD

**Issue by jspaaks** [ardc-fair-checklist/ardc-fair-checklist.github.io#75]
code state: d447c22d3bf175dea68f0cf917c53f743d9efe1b

![image](https://user-images.githubusercontent.com/4558105/231206244-2bc7247a-fff3-44e8-8750-738a5b779af7.png)

FWIW, here's some more phrases we had:

Tom: I’ve been thinking a gap in this approach is filtering out types of software that are not in scope. For instance, deployed or live services. Software not used for research (maybe).

“This tool is intended for …” focus on the middle type (prototypes)
Maybe some wording about how it is available excluding commercial software
Code you’ve written, not the code you’ve used

“About you: you’re an creator of software…”

After we make changes, it's probably a good idea to revisit the questions and check that they make sense given the scope definition.

**Comment by jspaaks** [comment]
I think I'm happy with the scoping for the moment.

- In the unexpanded preamble of the software checklist, we have "research software authors" and a definition of "the software".
- In the expanded/on-demand text, there is more detail available about what metadata should be included (only "bundled") and what should not be included (anything from APIs). It also differentiates between human readable metadata (READMEs and such) v machine readable metadata (CITATION.cff, pyproject.toml, .zenodo.json, etc). 
- While the text is not explicit, it is clear that the checklist is not meant for assessing a service (but it could be used to assess the software of such a service).

If you agree @tom-h, I would like to close this issue.

**Comment by tom-h** [comment]
In the interests of getting this out there, I basically agree. I like the benefits and "calls to action" you've included. I think that is a great way to frame it.

I had imagined making the scope narrower, but it's implied. For instance, we assume openly available software... but then where else would they put their badge? So I think we can leave it as is.
