### ISSUE TITLE
Review phrasing of question about search engines / indexing

### ISSUE THREAD

**Issue by jspaaks** [ardc-fair-checklist/ardc-fair-checklist.github.io#80]
code state: f0201323c3a472055878058dd4188d2b0e545695

![image](https://user-images.githubusercontent.com/4558105/231442323-4bd6a0ce-5ddf-4c40-96fa-991d8715f267.png)

![image](https://user-images.githubusercontent.com/4558105/231447100-c6b5af78-b7c8-4fe0-81cc-ff304bee580c.png)

**Comment by jspaaks** [comment]
(From a note to myself, the answers could be) 

1. No
1. No, but some of the metadata is machine-readable
1. No, the software is on GitHub, GitLab or an other platform with minimal Search Engine Optimization
1. Yes, the software is linked from an associated web page which employs Search Engine Optimization. Tools such as validator.schema.org or OpenLink Data Sniffer confirm that the metadata can be picked up by indexers.

**Comment by jspaaks** [comment]
Updated to:

![image](https://user-images.githubusercontent.com/4558105/237050175-37fdfbcc-04a5-4e75-aba3-e76123af4a87.png)

I think it's good enough for now. Let's do some user testing, see what we learn.

**Comment by tom-h** [comment]
Yes, agree
