### ISSUE TITLE
Revisit phrasing of version strategy question

### ISSUE THREAD

**Issue by jspaaks** [ardc-fair-checklist/ardc-fair-checklist.github.io#81]
code state: f0201323c3a472055878058dd4188d2b0e545695

![image](https://user-images.githubusercontent.com/4558105/231444510-15b82644-a14f-4a08-b497-392a362450df.png)

![image](https://user-images.githubusercontent.com/4558105/231444549-7fd2680b-698e-4db4-befe-37b8b8b5bc44.png)

**Comment by jspaaks** [comment]
Updated to:

![image](https://user-images.githubusercontent.com/4558105/234543234-840ca3f1-56e5-4be1-b4c6-0b06f87f7a29.png)

**Comment by jspaaks** [comment]
With this latest change, I would like to close this issue, what do you think @tom-h?

**Comment by tom-h** [comment]
Very close. "different versions of the software are not identified separately" is a bit difficult to parse. "reflect interoperability aspects" in the final answer is really opaque.

But, the points/levels of differentiation are good. I prefer the explanatory text over the wording you've given for the answers. A combination might be better like:
- the software does not make releases, or different versions are not identified
 (e.g., updates may or may not be available, but when they are, no version or release is indicated)
- (second answer and example are spot on)
- As previous answer, but the version identifier is labelled according to a [software versioning scheme](https://en.wikipedia.org/wiki/Software_versioning#Schemes)
 (e.g., popular schemes include semantic versioning, calendar versioning. Some software communities may require a specific scheme to be used)

**Comment by jspaaks** [comment]
- I don't think calendar versioning should be part of the third bullet point above, because it is a plain sequence, i.e. second bullet point.
- Perhaps we could consider replacing the "interoperability" from the third answer with "compatibility"?, something like "As previous answer, and additionally, the version identifier communicates information about compatibility"

**Comment by jspaaks** [comment]
Updated to: 

![image](https://user-images.githubusercontent.com/4558105/237061512-1220c59a-2dc5-4c4e-abee-f54037960ce3.png)

**Comment by jspaaks** [comment]
Updated to:

![image](https://user-images.githubusercontent.com/4558105/237063070-bbe45a6d-7bee-4311-a12a-f12d8804f5dd.png)

**Comment by jspaaks** [comment]
With these latest changes, I think we can close this issue.

**Comment by tom-h** [comment]
agree
