### ISSUE TITLE
Consider adding a provenance question

### ISSUE THREAD

**Issue by jspaaks** [ardc-fair-checklist/ardc-fair-checklist.github.io#82]
code state: 51f96f163ac4d381e246356ea904e941b8c48a18

This issue is based on a comment by @tom-h in the Google Doc

Currently the list of questions does leave out some provenance aspects. We could add a question like:

How much detail is given about the origins of the project?
1. No detail per below is given
1. The authors (including changes) and their backgrounds, the resources such as mentoring, funding and institutional support are, the phases in developments and other provenance detail is described in textual form in a README or similar
1. As above, but the detail is available in a formal metadata format such as PROV-O

**Comment by jspaaks** [comment]
This post is also based on a comment by @tom-h in the Google Doc

>If applicable, how are the relationships to software that is not a dependency described?
>1. Not at all (but applicable)
>1. In the context of question 16 (or not applicable)
>
>Explanatory text: this would include references to papers or software that inspired the work, code snippets incorporated into the work, or the software the work was derived from (e.g., as a fork).

![image](https://user-images.githubusercontent.com/4558105/231451344-81e08f49-3603-430f-aebd-13e98fda4b76.png)

**Comment by tom-h** [comment]
The principles ask separately for qualified references to software, and for rich provenance metadata. I don't think these should be merged after all. I think the suggested text in https://github.com/ardc-fair-checklist/ssg/commit/51f96f163ac4d381e246356ea904e941b8c48a18 is sufficient and we could close this.

**Comment by jspaaks** [comment]
Nice, closing this one
