### ISSUE TITLE
Question 2 should be under findable

### ISSUE THREAD

**Issue by tom-h** [ardc-fair-checklist/ardc-fair-checklist.github.io#88]
code state: 390fb39dd3ac909ed699a12ef9d01b2d5a75a65a

Q 2 "Are the software's identifiers globally unique?" should be under "findable", and it's currently under accessible. The corresponding FAIR4RS guiding principle is "F1. Software is assigned a globally unique and persistent identifier."

**Comment by jspaaks** [comment]
I realize it's perhaps not the most widely shared view, but in my opinion having a globally unique identifier does not help another person find (as in "discover") the software. It does however help them unambigously resolve the identifier (uniqueness), in a way that will work for the foreseeable future (persistence), but importantly note this happens _after_ they found the identifier.

I think your question was also discussed in the Google Doc, where we talked about whether metadata that is "indexable" is helping discoverability. Something along the lines of:

![image](https://github.com/ardc-fair-checklist/ssg/assets/4558105/cebf1ad4-d19c-4cc1-a015-d9d18be76cb1)

 In my opinion, the answer is "no", instead what you're looking for as a desirable property is "indexed", not "indexable". Hence the phrasing of question 1.

**Comment by tom-h** [comment]
A resolver is an augmentation to the identifier. The "identifier" is only the string that differentiates it from others. And, you're right, it doesn't help discover the software. And you'd be correct that indexed would capture this. I don't solidly recall the discussion around F4 ("indexable") but I suspect the argument ran was that this was about the software curation/preparation by the software owner/author, rather than the properties of the infrastructure which it was captured in. This is something worth taking back to the group at the 2 year anniversary which is coming up in March 2025.  

As I understand it, the mindset comes from printed scholarly works. The identifier helps "find" the software based on a reference to it. i.e., if one stumbles across a reference to the software in a scholarly article, they could locate it using the identifier. The name of the project, or the name of the software wouldn't be sufficient in every instance. Especially if that name had already been used elsewhere.

That was the intent of the principle, and that's why this question belongs under findable. The way you're interpreting the principle is outside the intent with which it was written. So, I still think this belongs under F.

**Comment by jspaaks** [comment]
PR #90 moved question 2 from Accessibility to Findability. Closing this issue.
